<?php
require_once __DIR__ . '/../bootstrap.php';
require_admin_login();

function in_str($k,$m=null){$v=isset($_POST[$k])?trim((string)$_POST[$k]):''; if($m!==null&&function_exists('mb_substr')){$v=mb_substr($v,0,(int)$m,'UTF-8');} return $v;}
function in_int($k,$d=0){if(!isset($_POST[$k])||$_POST[$k]==='')return (int)$d; return (int)$_POST[$k];}
function ensure_workgroups_table($db){$db->exec("CREATE TABLE IF NOT EXISTS workgroups (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, group_code VARCHAR(50) NULL, group_name VARCHAR(191) NOT NULL, sort_order INT NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, note TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_group_code (group_code), UNIQUE KEY uq_group_name (group_name), INDEX idx_sort_order (sort_order), INDEX idx_is_active (is_active)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}
function ensure_subdepartments_table($db){$db->exec("CREATE TABLE IF NOT EXISTS subdepartments (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, workgroup_id INT UNSIGNED NOT NULL, subdepartment_code VARCHAR(50) NULL, subdepartment_name VARCHAR(191) NOT NULL, sort_order INT NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, note TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_subdepartment_code (subdepartment_code), UNIQUE KEY uq_workgroup_subname (workgroup_id, subdepartment_name), INDEX idx_workgroup_id (workgroup_id), INDEX idx_sort_order (sort_order), INDEX idx_is_active (is_active), CONSTRAINT fk_subdepartments_workgroup FOREIGN KEY (workgroup_id) REFERENCES workgroups(id) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}

$error=null; $editItem=null;
try{ensure_workgroups_table($db); ensure_subdepartments_table($db);}catch(Exception $e){$error='ไม่สามารถเตรียมตารางแผนกย่อยได้';}

$workgroupOptions=array();
if($error===null){$stWg=$db->query('SELECT id, group_name FROM workgroups WHERE is_active=1 ORDER BY sort_order ASC, group_name ASC'); $workgroupOptions=$stWg->fetchAll(PDO::FETCH_ASSOC);}

if($_SERVER['REQUEST_METHOD']==='POST'&&$error===null){
$action=isset($_POST['action'])?trim((string)$_POST['action']):'';
if($action==='save'){
$id=in_int('id',0); $workgroupId=in_int('workgroup_id',0); $code=in_str('subdepartment_code',50); $name=in_str('subdepartment_name',191); $sort=in_int('sort_order',0); $active=in_int('is_active',1)===1?1:0; $note=in_str('note',4000);
if($workgroupId<=0){$error='กรุณาเลือกกลุ่มงาน';}
elseif($name===''){$error='กรุณากรอกชื่อแผนกย่อย';}
else{try{
if($id>0){$st=$db->prepare('UPDATE subdepartments SET workgroup_id=:workgroup_id, subdepartment_code=:subdepartment_code, subdepartment_name=:subdepartment_name, sort_order=:sort_order, is_active=:is_active, note=:note, updated_at=NOW() WHERE id=:id LIMIT 1'); $st->execute(array('workgroup_id'=>$workgroupId,'subdepartment_code'=>$code!==''?$code:null,'subdepartment_name'=>$name,'sort_order'=>$sort,'is_active'=>$active,'note'=>$note!==''?$note:null,'id'=>$id)); flash('success','แก้ไขแผนกย่อยเรียบร้อยแล้ว');}
else{$st=$db->prepare('INSERT INTO subdepartments (workgroup_id,subdepartment_code,subdepartment_name,sort_order,is_active,note,created_at,updated_at) VALUES (:workgroup_id,:subdepartment_code,:subdepartment_name,:sort_order,:is_active,:note,NOW(),NOW())'); $st->execute(array('workgroup_id'=>$workgroupId,'subdepartment_code'=>$code!==''?$code:null,'subdepartment_name'=>$name,'sort_order'=>$sort,'is_active'=>$active,'note'=>$note!==''?$note:null)); flash('success','เพิ่มแผนกย่อยเรียบร้อยแล้ว');}
redirect('/nurse_srnh/admin/subdepartments.php');
}catch(PDOException $e){$error=((int)$e->getCode()===23000)?'รหัสซ้ำ หรือชื่อแผนกย่อยซ้ำในกลุ่มงานเดียวกัน':'บันทึกข้อมูลไม่สำเร็จ';}}
}
if($action==='delete'){$id=in_int('id',0); if($id>0){$st=$db->prepare('DELETE FROM subdepartments WHERE id=:id LIMIT 1');$st->execute(array('id'=>$id)); flash('success','ลบแผนกย่อยเรียบร้อยแล้ว');} redirect('/nurse_srnh/admin/subdepartments.php');}
}

if(isset($_GET['edit'])&&(int)$_GET['edit']>0){$st=$db->prepare('SELECT * FROM subdepartments WHERE id=:id LIMIT 1');$st->execute(array('id'=>(int)$_GET['edit']));$editItem=$st->fetch(PDO::FETCH_ASSOC);} 

$q=isset($_GET['q'])?trim((string)$_GET['q']):''; $status=isset($_GET['status'])?trim((string)$_GET['status']):'all'; $wgFilter=isset($_GET['workgroup_id'])?(int)$_GET['workgroup_id']:0;
$sql='SELECT sd.*, wg.group_name FROM subdepartments sd INNER JOIN workgroups wg ON wg.id=sd.workgroup_id WHERE 1=1'; $params=array();
if($q!==''){ $sql.=' AND (sd.subdepartment_name LIKE :q OR sd.subdepartment_code LIKE :q OR wg.group_name LIKE :q)'; $params['q']='%'.$q.'%'; }
if($status==='active')$sql.=' AND sd.is_active=1'; elseif($status==='inactive')$sql.=' AND sd.is_active=0';
if($wgFilter>0){$sql.=' AND sd.workgroup_id=:workgroup_id'; $params['workgroup_id']=$wgFilter;}
$sql.=' ORDER BY wg.sort_order ASC, sd.sort_order ASC, sd.id DESC';
$st=$db->prepare($sql); $st->execute($params); $items=$st->fetchAll(PDO::FETCH_ASSOC);

$title='จัดการแผนกย่อย'; $success=flash('success'); include __DIR__.'/_header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end mb-3 gap-2"><div><h1 class="page-title h3 mb-1">จัดการแผนกย่อยของกลุ่มงาน</h1><p class="text-soft mb-0">แผนกย่อยต้องผูกกับกลุ่มงานเสมอ</p></div></div>
<?php if($success): ?><div class="alert alert-success glass-card border-0"><?= h($success) ?></div><?php endif; ?>
<?php if($error): ?><div class="alert alert-danger glass-card border-0"><?= h($error) ?></div><?php endif; ?>
<div class="row g-4">
<div class="col-xl-5"><div class="glass-card p-4"><h2 class="h5 mb-3"><?= $editItem?'แก้ไขแผนกย่อย #'.(int)$editItem['id']:'เพิ่มแผนกย่อยใหม่' ?></h2><form method="post"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= h(isset($editItem['id'])?$editItem['id']:'') ?>"><div class="row g-3"><div class="col-md-6"><label class="form-label">กลุ่มงาน <span class="text-danger">*</span></label><select class="form-select" name="workgroup_id" required><option value="">-- เลือกกลุ่มงาน --</option><?php foreach($workgroupOptions as $wg): ?><option value="<?= (int)$wg['id'] ?>" <?= (isset($editItem['workgroup_id'])&&(int)$editItem['workgroup_id']===(int)$wg['id'])?'selected':'' ?>><?= h($wg['group_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">รหัสแผนกย่อย</label><input class="form-control" name="subdepartment_code" maxlength="50" value="<?= h(isset($editItem['subdepartment_code'])?$editItem['subdepartment_code']:'') ?>"></div><div class="col-12"><label class="form-label">ชื่อแผนกย่อย <span class="text-danger">*</span></label><input class="form-control" name="subdepartment_name" maxlength="191" required value="<?= h(isset($editItem['subdepartment_name'])?$editItem['subdepartment_name']:'') ?>"></div><div class="col-md-6"><label class="form-label">Sort</label><input class="form-control" type="number" name="sort_order" value="<?= h((string)(isset($editItem['sort_order'])?$editItem['sort_order']:0)) ?>"></div><div class="col-md-6"><label class="form-label">สถานะ</label><select class="form-select" name="is_active"><option value="1" <?= (!isset($editItem['is_active'])||(int)$editItem['is_active']===1)?'selected':'' ?>>Active</option><option value="0" <?= (isset($editItem['is_active'])&&(int)$editItem['is_active']===0)?'selected':'' ?>>Inactive</option></select></div><div class="col-12"><label class="form-label">หมายเหตุ</label><textarea class="form-control" name="note" rows="3"><?= h(isset($editItem['note'])?$editItem['note']:'') ?></textarea></div></div><div class="d-flex gap-2 mt-3"><button class="btn btn-brand" type="submit">บันทึก</button><a class="btn btn-outline-secondary" href="/nurse_srnh/admin/subdepartments.php">ล้างฟอร์ม</a></div></form></div></div>
<div class="col-xl-7"><div class="glass-card p-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><h2 class="h5 mb-0">รายการแผนกย่อย</h2><form method="get" class="d-flex gap-2"><select class="form-select form-select-sm" name="workgroup_id"><option value="0">ทุกกลุ่มงาน</option><?php foreach($workgroupOptions as $wg): ?><option value="<?= (int)$wg['id'] ?>" <?= $wgFilter===(int)$wg['id']?'selected':'' ?>><?= h($wg['group_name']) ?></option><?php endforeach; ?></select><input class="form-control form-control-sm" name="q" placeholder="ค้นหา" value="<?= h($q) ?>"><select class="form-select form-select-sm" name="status"><option value="all" <?= $status==='all'?'selected':'' ?>>ทั้งหมด</option><option value="active" <?= $status==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $status==='inactive'?'selected':'' ?>>Inactive</option></select><button class="btn btn-sm btn-outline-primary" type="submit">กรอง</button></form></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th style="width:70px;">ID</th><th>แผนกย่อย</th><th style="width:120px;">กลุ่มงาน</th><th style="width:80px;">Sort</th><th style="width:110px;">สถานะ</th><th style="width:140px;"></th></tr></thead><tbody><?php foreach($items as $it): ?><tr><td>#<?= (int)$it['id'] ?></td><td><div class="fw-semibold"><?= h($it['subdepartment_name']) ?></div><div class="small text-soft"><?= h((string)$it['subdepartment_code']) ?></div></td><td><?= h($it['group_name']) ?></td><td><?= (int)$it['sort_order'] ?></td><td><?= (int)$it['is_active']===1?'<span class="badge text-bg-success">Active</span>':'<span class="badge text-bg-secondary">Inactive</span>' ?></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="/nurse_srnh/admin/subdepartments.php?edit=<?= (int)$it['id'] ?>">แก้ไข</a><form method="post" class="d-inline" onsubmit="return confirm('ยืนยันการลบ?');"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$it['id'] ?>"><button class="btn btn-sm btn-outline-danger" type="submit">ลบ</button></form></td></tr><?php endforeach; ?><?php if(count($items)===0): ?><tr><td colspan="6" class="text-center text-muted py-4">ยังไม่มีข้อมูลแผนกย่อย</td></tr><?php endif; ?></tbody></table></div></div></div>
</div>
<?php include __DIR__ . '/_footer.php'; ?>
